name: default-environment
channels:
  - emscripten-forge-4x
  - conda-forge
dependencies:
  # For the C++ notebook
  - xeus-cpp >=0.9
  - xsimd =14.*
  - xwidgets
  - xproperty
  - jupyterlab_widgets
  # For the Python notebook
  - xeus-python
  - polars
  - matplotlib
  - numpy
  - pyarrow
  - ipywidgets
